services:
  app:
    build: .
    container_name: prism-app
    restart: always
    ports:
      - "5051:5051"
    environment:
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./prism.db:/app/prism.db
    networks:
      - prism-net
      - shared-redis-net

networks:
  prism-net:
    driver: bridge
  shared-redis-net:
    external: true
